<?xml version="1.0" ?>
<definitions name="userclass" targetNamespace="urn:userclass" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:userclass" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
<types xmlns="http://schemas.xmlsoap.org/wsdl/" />
<portType name="userclassPort"><operation name="doit">
<input message="tns:doitRequest" />
<output message="tns:doitResponse" />
</operation>
</portType>
<binding name="userclassBinding" type="tns:userclassPort">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
<operation name="doit">
<soap:operation soapAction="urn:userclass#userclass#doit" />
<input><soap:body use="encoded" namespace="urn:userclass" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</input>
<output>
<soap:body use="encoded" namespace="urn:userclass" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</output>
</operation>
</binding>
<service name="userclass">
<documentation />
<port name="userclassPort" binding="tns:userclassBinding"><soap:address location="http://127.0.0.1:8080/userclass_server.php" />
</port>
</service>
<message name="doitRequest">
<part name="a" type="xsd:string" />
</message>
<message name="doitResponse">
<part name="doit" type="xsd:string" />
</message>
</definitions>